---
version: 1
formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S.%f"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: "/var/log/cdim/app_migration_procedures.log"
    maxBytes: 3000000
    backupCount: 12
    encoding: "utf-8"
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file]
