---
log:
  logging_level: INFO
  log_dir: /var/log/cdim
  file: app_migration_procedures.log
  rotation_size: 3000000
  backup_files: 12
  stdout: false
migration_procedures:
  host: 0.0.0.0
  port: 8003
